### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by ozanmuyes** [mxstbr/urql-exchange-schema#2]
Hi there,

Coming from the GraphCDN's video and I saw the description of the repo. You didn't change it back, just a quick reminder :)

Thanks for the CDN and all other good work.

Have a good one.

**Comment by mxstbr** [comment]
Hah, I left that in there on purpose as a little easter egg for anyone checking after watching the GraphCDN video — glad to hear somebody did! 😉 Thank you for pinging me about it.
